import Head from "next/head";
import React from "react";
import { withLayout } from "../components/modules/layout/Layout";
import styles from "../styles/Home.module.css";

function Home() {
  return (
    <>
      <Head>
        <title>Technoteka Moscow</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>Welcome to Technoteka Moscow from Anton</p>
        </div>
      </main>
    </>
  );
}

export default withLayout(Home);
